version: "3.8"
services:
  front:
    build: ./
    container_name: node-server
    volumes:
      - ./front:/root/front
    working_dir: '/root/front'
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true